### ISSUE TITLE
Regarding Mirror Effect

### ISSUE THREAD

**Issue by nitinmaru** [federico-mammano/Looking-Through-Oculus-Rift#1]
Hello 
I am looking for a solution to view HMD display in Desktop 
if you can help me for that i will appreciate your help

Thank you
nitin maru
maru.nitin111@gmail.com

**Comment by federico-mammano** [comment]
Hi Nitin,

It is unclear to me what you are looking for.
Would you mind telling me more about your purpose?

Thanks,
Federico

**Comment by nitinmaru** [comment]
Hello Federico,
FIrst of all thank you for your quick reply

Here is what i want to implement

I can see rendered Images in HMD(my camera output) and i want to render same output to my PC display at a same time so that person sitting behind HMD operator can also see what is excatly displayed in HMD.

I hope its quiet little problem according to you and i think it helps me a lot of way

Looking for kind solution
Thank you

**Comment by federico-mammano** [comment]
https://developer.oculus.com/documentation/pcsdk/0.4/concepts/dg-device-mgmt/#dg-device-mgmt-id

**Comment by nitinmaru** [comment]
Hi there
I tried Duplicating Dk2 Monitor to Main monitor but it still not working
may be there is something i am missing

**Comment by nitinmaru** [comment]
can you guide me for what i missed?

**Comment by nitinmaru** [comment]
Hello sir
I am trying to render same project Using SDK 0.5.0.1 
can you provide me infirmation for same as I gor stuck in "GLEContext" LIne 702 on Win32_OGLApputil.h

**Comment by nitinmaru** [comment]
HI
i am facing issue regarding render camera output in desktop window
actually everything is fine in HMD
but in Desktop window i can see only half size of camera output and other half is not showing basically
its video capture width and height is more than it should be
i also try to upload here image but it displays an error for same
Kindly provide suggestion

**Comment by nitinmaru** [comment]
here is snap of what it displays
![capture](https://cloud.githubusercontent.com/assets/14993528/12882353/1304e09e-ce77-11e5-8fc4-b8927f5fb656.PNG)

**Comment by nitinmaru** [comment]
waiting for your kind response
Thank you in advance
