### ISSUE TITLE
Seams not to work with CV1

### ISSUE THREAD

**Issue by TraxXavier** [federico-mammano/Looking-Through-Oculus-Rift#2]
Hello

I tried your sample with an Oculus CV1 and it failed saying that it can not find the headset.
Is there a simple way to resolve the compatibility issue?

Cheers
Trax

**Comment by federico-mammano** [comment]
Hi,

I shared this project in the mists of time to help VR pioneers struggling with first HMD prototypes. Unfortunately, at that time, it was mainly tested with the oculus rift dk2. However, even if HMDs today are better, the theory behind is still valid and the same.
